// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateAccount(arg1:models.Account):Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function GetAllAccounts():Promise<Array<models.Account>>;
