// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1) {
  return window['go']['services']['AccountService']['CreateAccount'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['services']['AccountService']['DeleteAccount'](arg1);
}

export function GetAllAccounts() {
  return window['go']['services']['AccountService']['GetAllAccounts']();
}
