// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUrl(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PostUrl(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function PostWithQuery(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
