// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUrl(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetUrl'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PostUrl(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PostUrl'](arg1, arg2, arg3, arg4, arg5);
}

export function PostWithQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PostWithQuery'](arg1, arg2, arg3, arg4);
}
